#!/bin/bash
set -euo pipefail

# ViT-L @256 fp32 fulltrain, 1s concat_ar, p01_fixed split, output regularization.
# This script keeps the regularizer isolated to this run by exporting explicit
# LORA_OUTPUT_REG_* values; normal submit scripts keep weight=0/default behavior.

PROJECT_ROOT="${PROJECT_ROOT:-/path/to/VJEPA2-EXP}"
RUN_SCRIPT="${PROJECT_ROOT}/scripts/run_hdepic_single_probe_encoder_lora_gaze_pose_matrix_h100.slurm"
WORKERS="${EVAL_NUM_WORKERS:-4}"
VAL_WORKERS="${EVAL_VAL_NUM_WORKERS:-${WORKERS}}"
REG_MODE="${LORA_OUTPUT_REG_MODE:-confidence_penalty}"
REG_WEIGHT="${LORA_OUTPUT_REG_WEIGHT:-0.01}"
REG_TARGETS="${LORA_OUTPUT_REG_TARGETS:-verb|noun|action}"
TAG="${LORA_TAG:-hdepic-singleprobe-1s-p01fixed-regcp-w0p01-vitl-fp32-bs8-noac-10ep-w${WORKERS}}"
CONFIG_PATH="${CONFIG_PATH:-${PROJECT_ROOT}/configs/generated/hdepic_singleprobe_1s_p01fixed_reg_vitl_fp32_bs8_noac_fulltrain.yaml}"
CHECKPOINT="${CHECKPOINT:-${PROJECT_ROOT}/checkpoints/vitl.pt}"
SLURM_TIME="${SLURM_TIME:-72:00:00}"
PATIENCE="${EVAL_EARLY_STOPPING_PATIENCE:-3}"

export_csv="NONE"
export_csv+=",PROJECT_ROOT=${PROJECT_ROOT}"
export_csv+=",LORA_TAG=${TAG}"
export_csv+=",CONFIG_PATH=${CONFIG_PATH}"
export_csv+=",CHECKPOINT=${CHECKPOINT}"
export_csv+=",BACKBONE=vitl"
export_csv+=",EVAL_RESOLUTION=256"
export_csv+=",DEBUG_SUBSET_PATH="
export_csv+=",HDEPIC_DIRECT_ROPE_10S=0"
export_csv+=",HDEPIC_AR10S_SLIDING_GAZE_POSE=0"
export_csv+=",AR10S_SLIDING_PROBE=0"
export_csv+=",EVAL_ANTICIPATION_SEC="
export_csv+=",EVAL_TRAIN_ANTICIPATION_SEC_MIN="
export_csv+=",EVAL_TRAIN_ANTICIPATION_SEC_MAX="
export_csv+=",EVAL_MAX_TRAIN_ITERS=0"
export_csv+=",EVAL_NUM_EPOCHS=10"
export_csv+=",EVAL_VAL_EVERY=1"
export_csv+=",EVAL_BEST_METRIC=val-action-acc"
export_csv+=",EVAL_EARLY_STOPPING_PATIENCE=${PATIENCE}"
export_csv+=",RESUME_CHECKPOINT=0"
export_csv+=",EVAL_SINGLE_PROBE=1"
export_csv+=",LORA_PROBE_TRAIN_MODE=full"
export_csv+=",EVAL_LR=0.0001"
export_csv+=",EVAL_BATCH_SIZE=8"
export_csv+=",EVAL_GRAD_CLIP=1.0"
export_csv+=",EVAL_WARMUP_EPOCHS=2"
export_csv+=",ENCODER_LORA_RANK=8"
export_csv+=",ENCODER_LORA_ALPHA=16.0"
export_csv+=",ENCODER_LORA_LAST_N_BLOCKS=0"
export_csv+=",ENCODER_LORA_LR_MULT=0.5"
export_csv+=",ENCODER_LORA_TARGET_SUFFIXES=attn.qkv|attn.proj"
export_csv+=",ENCODER_LORA_ACTIVATION_CHECKPOINTING=0"
export_csv+=",BINARY_INPUT_ADAPTER_ACTIVATION_CHECKPOINTING=0"
export_csv+=",LORA_PRETRAINED_PROBE="
export_csv+=",LORA_OUTPUT_REG_MODE=${REG_MODE}"
export_csv+=",LORA_OUTPUT_REG_WEIGHT=${REG_WEIGHT}"
export_csv+=",LORA_OUTPUT_REG_TARGETS=${REG_TARGETS}"
export_csv+=",LORA_VAL_METRIC_SCOPE=native"
export_csv+=",LORA_VAL_METRIC_AGGREGATION=metric_wise_max"
export_csv+=",EVAL_USE_BFLOAT16=0"
export_csv+=",EVAL_NUM_WORKERS=${WORKERS}"
export_csv+=",EVAL_VAL_NUM_WORKERS=${VAL_WORKERS}"

echo "[submit-vitl-1s-p01fixed-reg-fulltrain] tag=${TAG}"
echo "[submit-vitl-1s-p01fixed-reg-fulltrain] split=p01_fixed via current HD_EPIC_*_vjepa.csv; reg=${REG_MODE} weight=${REG_WEIGHT} targets=${REG_TARGETS}; patience=${PATIENCE}"
sbatch --time="${SLURM_TIME}" --export="${export_csv}" "${RUN_SCRIPT}"
