#!/bin/bash
set -euo pipefail

# H200 AR10s 3-step rollout launcher: pass EVAL_BATCH_SIZE (default 8).
# Default is bs8/w4. If CUDA OOM, relaunch with EVAL_BATCH_SIZE=6; if cgroup
# OOM, relaunch with EVAL_NUM_WORKERS=2. For full train, use
# EVAL_MAX_TRAIN_ITERS=0 EVAL_NUM_EPOCHS=10 EVAL_VAL_EVERY=2.

PROJECT_ROOT="${PROJECT_ROOT:-/path/to/VJEPA2-EXP}"
RUN_SCRIPT="${PROJECT_ROOT}/scripts/run_hdepic_singleprobe_ar10s_h200.slurm"
BS="${EVAL_BATCH_SIZE:-8}"
ITERS="${EVAL_MAX_TRAIN_ITERS:-10}"
EPOCHS="${EVAL_NUM_EPOCHS:-1}"
VAL_EVERY="${EVAL_VAL_EVERY:-1}"
AR_STEPS="${HDEPIC_AR_STEPS:-3}"
WORKERS="${EVAL_NUM_WORKERS:-4}"
VAL_WORKERS="${EVAL_VAL_NUM_WORKERS:-${WORKERS}}"
TAG="${LORA_TAG:-hdepic-ar10s-h200-sliding${AR_STEPS}-bs${BS}-w${WORKERS}-probe-i${ITERS}}"
CONFIG_PATH="${CONFIG_PATH:-${PROJECT_ROOT}/configs/generated/hdepic_singleprobe_ar10s_sliding_gaze_pose_enclora_fulltrain.yaml}"
CHECKPOINT="${CHECKPOINT:-${PROJECT_ROOT}/checkpoints/vitl.pt}"
SBATCH_MEM="${SBATCH_MEM:-240GB}"
SBATCH_TIME="${SBATCH_TIME:-04:00:00}"

export_csv="ALL,PROJECT_ROOT=${PROJECT_ROOT},LORA_TAG=${TAG},CONFIG_PATH=${CONFIG_PATH},CHECKPOINT=${CHECKPOINT},BACKBONE=vitl,EVAL_RESOLUTION=256,HDEPIC_AR10S_SLIDING_GAZE_POSE=1,HDEPIC_AR_STEPS=${AR_STEPS},MODEL_NUM_STEPS=${AR_STEPS},EVAL_ANTICIPATION_SEC=10,EVAL_TRAIN_ANTICIPATION_SEC_MIN=8,EVAL_TRAIN_ANTICIPATION_SEC_MAX=10,MODEL_RETURN_MODE=final_window,MODEL_MAX_ROLLOUT_STEPS=512,EVAL_GPUS=1,EVAL_MAX_TRAIN_ITERS=${ITERS},EVAL_NUM_EPOCHS=${EPOCHS},EVAL_VAL_EVERY=${VAL_EVERY},EVAL_BEST_METRIC=val-action-acc,EVAL_EARLY_STOPPING_PATIENCE=0,RESUME_CHECKPOINT=0,EVAL_SINGLE_PROBE=1,LORA_PROBE_TRAIN_MODE=full,EVAL_LR=0.0001,EVAL_BATCH_SIZE=${BS},EVAL_GRAD_CLIP=1.0,EVAL_WARMUP_EPOCHS=2,ENCODER_LORA_RANK=8,ENCODER_LORA_ALPHA=16.0,ENCODER_LORA_LAST_N_BLOCKS=0,ENCODER_LORA_LR_MULT=0.5,ENCODER_LORA_TARGET_SUFFIXES=attn.qkv|attn.proj,ENCODER_LORA_ACTIVATION_CHECKPOINTING=0,BINARY_INPUT_ADAPTER_ACTIVATION_CHECKPOINTING=0,LORA_PRETRAINED_PROBE=,EVAL_USE_BFLOAT16=0,EVAL_NUM_WORKERS=${WORKERS},EVAL_VAL_NUM_WORKERS=${VAL_WORKERS},PERF_MONITOR=1,PERF_INTERVAL=30"

echo "[submit-ar10s-h200] H200 bs=${BS} workers=${WORKERS} ar_steps=${AR_STEPS} iters=${ITERS} epochs=${EPOCHS} val_every=${VAL_EVERY} mem=${SBATCH_MEM} time=${SBATCH_TIME} tag=${TAG}"
sbatch --mem="${SBATCH_MEM}" --time="${SBATCH_TIME}" --export="${export_csv}" "${RUN_SCRIPT}"
